### ISSUE TITLE
Check kernel's vulnerability based on uname instead of installed packages

### ISSUE THREAD

**Issue by 0x4D31** [0x4D31/salt-scanner#2]
If you have the old kernel packages installed, you will still get an alert showing that your host is vulnerable, even after a full update.

**Comment by 0x4D31** [comment]
It doesn't work for Debian based systems. Got the following error for Ubuntu:
`Error - Failed to parse package name kernel-4.4.0-1020-aws
`
The initial fix was a dirty workaround. Needs to be fixed for debian based systems (format of the kernel package name is different)
```
get_kernel function and the following lines in audit function should be changed. 
# remove kernel packages from the list
r = re.compile('kernel-[0-9]')
pkgs = filter(lambda i: not r.match(i), init_pkgs)
# OR pkgs = [i for i in init_pkgs if not r.match(i)]
# add kernel package to the list, based on uname:
kernelpkg = get_kernel(key)
if kernelpkg:
    pkgs.append(kernelpkg)
```

**Comment by hbokh** [comment]
FYI This still does not work. It errors with

`Error - Failed to parse package name linux-image-4.4.0-72-generic`

Vulners expects something like

`return "linux-image-4.4.0-72-generic 4.4.0-72.93 amd64"`

so with TWO extra arguments.
